apiVersion: v1
kind: Service
metadata:
  name: adminservice-service
  namespace: labourlink
  labels:
    app: adminservice-microservice
spec:
  selector:
    app: adminservice-microservice
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080 
    - name: https
      protocol: TCP
      port: 8081
      targetPort: 8081 
  type: ClusterIP
