services:
  users-microservice:
    image: authentication-microservice:latest
    build:
      context: /AuthenticationService
      dockerfile: /eCommerce.API/Dockerfile
    environment:
      - rabbitmq
    networks:
      - users-postgres-network
      - ecommerce-network
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  labourlink-network:
    driver: bridge
