apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"profile-service","namespace":"labourlink"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"profile-service"}},"template":{"metadata":{"labels":{"app":"profile-service"}},"spec":{"containers":[{"envFrom":[{"secretRef":{"name":"labourlink-secrets"}}],"image":"labourlinkcontainerregistry.azurecr.io/profileservice:latest","name":"profile-service","ports":[{"containerPort":80}],"volumeMounts":[{"mountPath":"/mnt/secrets","name":"secrets-store","readOnly":true}]}],"volumes":[{"csi":{"driver":"secrets-store.csi.k8s.io","readOnly":true,"volumeAttributes":{"secretProviderClass":"labourlink-keyvault-secrets"}},"name":"secrets-store"}]}}}}
  creationTimestamp: "2025-03-15T04:56:34Z"
  generation: 1
  name: profile-service
  namespace: labourlink
  resourceVersion: "1022661"
  uid: 4a1e5729-6447-4b03-b6cc-c31f8e2951e3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: profile-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: profile-service
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: labourlink-secrets
        image: labourlinkcontainerregistry.azurecr.io/profileservice:latest
        imagePullPolicy: Always
        name: profile-service
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/secrets
          name: secrets-store
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: labourlink-keyvault-secrets
        name: secrets-store
status:
  conditions:
  - lastTransitionTime: "2025-03-15T04:56:34Z"
    lastUpdateTime: "2025-03-15T04:56:34Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-03-15T07:26:16Z"
    lastUpdateTime: "2025-03-15T07:26:16Z"
    message: ReplicaSet "profile-service-5bc8bd7fb4" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
