apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: labourlink
  labels:
    app: profile-service
spec:
  selector:
    app: profile-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
