apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  namespace: labourlink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service
          image: labourlinkcontainerregistry.azurecr.io/profileservice:latest
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: https
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: JWT-ISSUER
              value: Labourlink-Api
            - name: JWT-AUDIENCE
              value: Labourlink-Frontend
            - name: CORS-ORIGIN
              value: http://localhost:5173
            - name: JWT-SECRET-KEY
              valueFrom:
                secretKeyRef:
                  name:  labourlink-secrets
                  key: JWT-SECRET-KEY
            - name: RABBITMQ-HOST
              valueFrom:
                secretKeyRef:
                  name:  labourlink-secrets
                  key: RABBITMQ-HOST
            - name: RABBITMQ-USERNAME
              valueFrom:
                secretKeyRef:
                  name:  labourlink-secrets
                  key: RABBITMQ-USERNAME
            - name: RABBITMQ-PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  labourlink-secrets
                  key: RABBITMQ-PASSWORD
            - name: CLOUDINARY-CLOUDNAME
              valueFrom:
                secretKeyRef:
                  name:  labourlink-secrets
                  key: CLOUDINARY-CLOUDNAME
            - name: CLOUDINARY-APIKEY
              valueFrom:
                secretKeyRef:
                  name:  labourlink-secrets
                  key: CLOUDINARY-APIKEY
            - name: CLOUDINARY-API-SECRET
              valueFrom:
                secretKeyRef:
                  name:  labourlink-secrets
                  key: CLOUDINARY-API-SECRET
            - name: DB-CONNECTION-STRING
              valueFrom:
                secretKeyRef:
                   name: labourlink-secrets
                   key : DB-CONNECTION-STRING
