apiVersion: v1
kind: Service
metadata:
  name: chatservice-service
  namespace: labourlink
  labels:
    app: chatservice-microservice
spec:
  selector:
    app: chatservice-microservice
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080 # Exposing HTTP on port 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443 # Exposing HTTPS on port 443, ensure your app supports this
  type: LoadBalancer
