apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: labourlink-keyvault-secrets
  namespace: labourlink
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "3b9da9d7-0b29-4521-ae5e-47879c544d31"
    keyvaultName: "labourlink-keyvault"
    tenantId: "7d1e92b4-eefc-4667-88e1-c11660a9cdaf"
    objects: |
      - objectName: "CLOUDINARY-API-SECRET"
        objectType: secret
      - objectName: "CLOUDINARY-APIKEY"
        objectType: secret
      - objectName: "CLOUDINARY-CLOUDNAME"
        objectType: secret
      - objectName: "DB-ConnectionString"
        objectType: secret
      - objectName: "JWT-SECRET-KEY"
        objectType: secret
      - objectName: "RabbitMQ-ErlangCookie"
        objectType: secret
      - objectName: "RabbitMQ-Host"
        objectType: secret
      - objectName: "RabbitMQ-Password"
        objectType: secret
      - objectName: "RabbitMQ-Username"
        objectType: secret
  secretObjects:
    - secretName: labourlink-secrets
      type: Opaque
      data:
        - key: "CLOUDINARY-API-SECRET"
          objectName: "CLOUDINARY-API-SECRET"
        - key: "CLOUDINARY-APIKEY"
          objectName: "CLOUDINARY-APIKEY"
        - key: "CLOUDINARY-CLOUDNAME"
          objectName: "CLOUDINARY-CLOUDNAME"
        - key: "DB-ConnectionString"
          objectName: "DB-ConnectionString"
        - key: "JWT-SECRET-KEY"
          objectName: "JWT-SECRET-KEY"
        - key: "RabbitMQ-ErlangCookie"
          objectName: "RabbitMQ-ErlangCookie"
        - key: "RabbitMQ-Host"
          objectName: "RabbitMQ-Host"
        - key: "RabbitMQ-Password"
          objectName: "RabbitMQ-Password"
        - key: "RabbitMQ-Username"
          objectName: "RabbitMQ-Username"